package com.example.cryptovista.network.model


import com.google.gson.annotations.SerializedName


data class CoinData(
    val id: String,
    val symbol: String,
    val name: String,
    @SerializedName("web_slug")
    val webSlug: String,
    @SerializedName("asset_platform_id")
    val assetPlatformId: Any,
    val platforms: Platforms,
    @SerializedName("detail_platforms")
    val detailPlatforms: DetailPlatforms,
    @SerializedName("block_time_in_minutes")
    val blockTimeInMinutes: Int,
    @SerializedName("hashing_algorithm")
    val hashingAlgorithm: String,
    val categories: List<String>,
    @SerializedName("preview_listing")
    val previewListing: Boolean,
    @SerializedName("public_notice")
    val publicNotice: Any,
    @SerializedName("additional_notices")
    val additionalNotices: List<Any>,
    val description: Description?,
    val links: Links?,
    val image: Image?,
    @SerializedName("country_origin")
    val countryOrigin: String,
    @SerializedName("genesis_date")
    val genesisDate: String,
    @SerializedName("sentiment_votes_up_percentage")
    val sentimentVotesUpPercentage: Double?,
    @SerializedName("sentiment_votes_down_percentage")
    val sentimentVotesDownPercentage: Double?,
    @SerializedName("watchlist_portfolio_users")
    val watchlistPortfolioUsers: Int,
    @SerializedName("market_cap_rank")
    val marketCapRank: Int,
    @SerializedName("market_data")
    val marketData: MarketData?,
    @SerializedName("community_data")
    val communityData: CommunityData?,
    @SerializedName("developer_data")
    val developerData: DeveloperData?,
    @SerializedName("status_updates")
    val statusUpdates: List<Any>,
    @SerializedName("last_updated")
    val lastUpdated: String,
    val tickers: List<Ticker>
) {

    data class Platforms(
        @SerializedName("")
        val x: String
    )


    data class DetailPlatforms(
        @SerializedName("")
        val x: X?
    ) {

        data class X(
            @SerializedName("decimal_place")
            val decimalPlace: Any,
            @SerializedName("contract_address")
            val contractAddress: String
        )
    }


    data class Description(
        val en: String
    )


    data class Links(
        val homepage: List<String>,
        val whitepaper: String,
        @SerializedName("blockchain_site")
        val blockchainSite: List<String>,
        @SerializedName("official_forum_url")
        val officialForumUrl: List<String>,
        @SerializedName("chat_url")
        val chatUrl: List<String>,
        @SerializedName("announcement_url")
        val announcementUrl: List<String>,
        @SerializedName("twitter_screen_name")
        val twitterScreenName: String,
        @SerializedName("facebook_username")
        val facebookUsername: String,
        @SerializedName("bitcointalk_thread_identifier")
        val bitcointalkThreadIdentifier: Any,
        @SerializedName("telegram_channel_identifier")
        val telegramChannelIdentifier: String,
        @SerializedName("subreddit_url")
        val subredditUrl: String,
        @SerializedName("repos_url")
        val reposUrl: ReposUrl?
    ) {

        data class ReposUrl(
            val github: List<String>,
            val bitbucket: List<Any>
        )
    }


    data class Image(
        val thumb: String,
        val small: String,
        val large: String
    )


    data class MarketData(
        @SerializedName("current_price")
        val currentPrice: CurrentPrice?,
        @SerializedName("total_value_locked")
        val totalValueLocked: Any,
        @SerializedName("mcap_to_tvl_ratio")
        val mcapToTvlRatio: Any,
        @SerializedName("fdv_to_tvl_ratio")
        val fdvToTvlRatio: Any,
        val roi: Any,
        val ath: Ath?,
        @SerializedName("ath_change_percentage")
        val athChangePercentage: AthChangePercentage?,
        @SerializedName("ath_date")
        val athDate: AthDate?,
        val atl: Atl?,
        @SerializedName("atl_change_percentage")
        val atlChangePercentage: AtlChangePercentage?,
        @SerializedName("atl_date")
        val atlDate: AtlDate?,
        @SerializedName("market_cap")
        val marketCap: MarketCap?,
        @SerializedName("market_cap_rank")
        val marketCapRank: Int,
        @SerializedName("fully_diluted_valuation")
        val fullyDilutedValuation: FullyDilutedValuation?,
        @SerializedName("market_cap_fdv_ratio")
        val marketCapFdvRatio: Double?,
        @SerializedName("total_volume")
        val totalVolume: TotalVolume?,
        @SerializedName("high_24h")
        val high24h: High24h?,
        @SerializedName("low_24h")
        val low24h: Low24h?,
        @SerializedName("price_change_24h")
        val priceChange24h: Double,
        @SerializedName("price_change_percentage_24h")
        val priceChangePercentage24h: Double?,
        @SerializedName("price_change_percentage_7d")
        val priceChangePercentage7d: Double?,
        @SerializedName("price_change_percentage_14d")
        val priceChangePercentage14d: Double?,
        @SerializedName("price_change_percentage_30d")
        val priceChangePercentage30d: Double?,
        @SerializedName("price_change_percentage_60d")
        val priceChangePercentage60d: Double?,
        @SerializedName("price_change_percentage_200d")
        val priceChangePercentage200d: Double?,
        @SerializedName("price_change_percentage_1y")
        val priceChangePercentage1y: Double?,
        @SerializedName("market_cap_change_24h")
        val marketCapChange24h: Double?,
        @SerializedName("market_cap_change_percentage_24h")
        val marketCapChangePercentage24h: Double?,
        @SerializedName("price_change_24h_in_currency")
        val priceChange24hInCurrency: PriceChange24hInCurrency?,
        @SerializedName("price_change_percentage_1h_in_currency")
        val priceChangePercentage1hInCurrency: PriceChangePercentage1hInCurrency?,
        @SerializedName("price_change_percentage_24h_in_currency")
        val priceChangePercentage24hInCurrency: PriceChangePercentage24hInCurrency?,
        @SerializedName("price_change_percentage_7d_in_currency")
        val priceChangePercentage7dInCurrency: PriceChangePercentage7dInCurrency?,
        @SerializedName("price_change_percentage_14d_in_currency")
        val priceChangePercentage14dInCurrency: PriceChangePercentage14dInCurrency?,
        @SerializedName("price_change_percentage_30d_in_currency")
        val priceChangePercentage30dInCurrency: PriceChangePercentage30dInCurrency?,
        @SerializedName("price_change_percentage_60d_in_currency")
        val priceChangePercentage60dInCurrency: PriceChangePercentage60dInCurrency?,
        @SerializedName("price_change_percentage_200d_in_currency")
        val priceChangePercentage200dInCurrency: PriceChangePercentage200dInCurrency?,
        @SerializedName("price_change_percentage_1y_in_currency")
        val priceChangePercentage1yInCurrency: PriceChangePercentage1yInCurrency?,
        @SerializedName("market_cap_change_24h_in_currency")
        val marketCapChange24hInCurrency: MarketCapChange24hInCurrency?,
        @SerializedName("market_cap_change_percentage_24h_in_currency")
        val marketCapChangePercentage24hInCurrency: MarketCapChangePercentage24hInCurrency?,
        @SerializedName("total_supply")
        val totalSupply: Double?,
        @SerializedName("max_supply")
        val maxSupply: Double?,
        @SerializedName("circulating_supply")
        val circulatingSupply: Double?,
        @SerializedName("last_updated")
        val lastUpdated: String
    ) {

        data class CurrentPrice(
            val aed: Double,
            val ars: Double,
            val aud: Double,
            val bch: Double,
            val bdt: Double,
            val bhd: Double,
            val bmd: Double,
            val bnb: Double,
            val brl: Double,
            val btc: Double,
            val cad: Double,
            val chf: Double,
            val clp: Double,
            val cny: Double,
            val czk: Double,
            val dkk: Double,
            val dot: Double,
            val eos: Double,
            val eth: Double,
            val eur: Double,
            val gbp: Double,
            val gel: Double,
            val hkd: Double,
            val huf: Double,
            val idr: Double,
            val ils: Double,
            val inr: Double,
            val jpy: Double,
            val krw: Double,
            val kwd: Double,
            val lkr: Double,
            val ltc: Double,
            val mmk: Double,
            val mxn: Double,
            val myr: Double,
            val ngn: Double,
            val nok: Double,
            val nzd: Double,
            val php: Double,
            val pkr: Double,
            val pln: Double,
            val rub: Double,
            val sar: Double,
            val sek: Double,
            val sgd: Double,
            val thb: Double,
            @SerializedName("try")
            val tryX: Double,
            val twd: Double,
            val uah: Double,
            val usd: Double,
            val vef: Double,
            val vnd: Double,
            val xag: Double,
            val xau: Double,
            val xdr: Double,
            val xlm: Double,
            val xrp: Double,
            val yfi: Double,
            val zar: Double,
            val bits: Double,
            val link: Double,
            val sats: Double
        )


        data class Ath(
            val aed: Double,
            val ars: Double,
            val aud: Double,
            val bch: Double?,
            val bdt: Double,
            val bhd: Double,
            val bmd: Double,
            val bnb: Double,
            val brl: Double,
            val btc: Double?,
            val cad: Double,
            val chf: Double,
            val clp: Double,
            val cny: Double,
            val czk: Double,
            val dkk: Double,
            val dot: Double,
            val eos: Double,
            val eth: Double?,
            val eur: Double,
            val gbp: Double,
            val gel: Double,
            val hkd: Double,
            val huf: Double,
            val idr: Double,
            val ils: Double,
            val inr: Double,
            val jpy: Double,
            val krw: Double,
            val kwd: Double,
            val lkr: Double,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class AthChangePercentage(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class AthDate(
            val aed: String,
            val ars: String,
            val aud: String?,
            val bch: String?,
            val bdt: String?,
            val bhd: String?,
            val bmd: String?,
            val bnb: String?,
            val brl: String?,
            val btc: String?,
            val cad: String?,
            val chf: String?,
            val clp: String?,
            val cny: String?,
            val czk: String?,
            val dkk: String?,
            val dot: String?,
            val eos: String?,
            val eth: String?,
            val eur: String?,
            val gbp: String?,
            val gel: String?,
            val hkd: String?,
            val huf: String?,
            val idr: String?,
            val ils: String?,
            val inr: String?,
            val jpy: String?,
            val krw: String?,
            val kwd: String?,
            val lkr: String?,
            val ltc: String?,
            val mmk: String?,
            val mxn: String?,
            val myr: String?,
            val ngn: String?,
            val nok: String?,
            val nzd: String?,
            val php: String?,
            val pkr: String?,
            val pln: String?,
            val rub: String?,
            val sar: String?,
            val sek: String?,
            val sgd: String?,
            val thb: String?,
            @SerializedName("try")
            val tryX: String?,
            val twd: String?,
            val uah: String?,
            val usd: String?,
            val vef: String?,
            val vnd: String?,
            val xag: String?,
            val xau: String?,
            val xdr: String?,
            val xlm: String?,
            val xrp: String?,
            val yfi: String?,
            val zar: String?,
            val bits: String?,
            val link: String?,
            val sats: String?
        )


        data class Atl(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class AtlChangePercentage(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class AtlDate(
            val aed: String?,
            val ars: String?,
            val aud: String?,
            val bch: String?,
            val bdt: String?,
            val bhd: String?,
            val bmd: String?,
            val bnb: String?,
            val brl: String?,
            val btc: String?,
            val cad: String?,
            val chf: String?,
            val clp: String?,
            val cny: String?,
            val czk: String?,
            val dkk: String?,
            val dot: String?,
            val eos: String?,
            val eth: String?,
            val eur: String?,
            val gbp: String?,
            val gel: String?,
            val hkd: String?,
            val huf: String?,
            val idr: String?,
            val ils: String?,
            val inr: String?,
            val jpy: String?,
            val krw: String?,
            val kwd: String?,
            val lkr: String?,
            val ltc: String?,
            val mmk: String?,
            val mxn: String?,
            val myr: String?,
            val ngn: String?,
            val nok: String?,
            val nzd: String?,
            val php: String?,
            val pkr: String?,
            val pln: String?,
            val rub: String?,
            val sar: String?,
            val sek: String?,
            val sgd: String?,
            val thb: String?,
            @SerializedName("try")
            val tryX: String?,
            val twd: String?,
            val uah: String?,
            val usd: String?,
            val vef: String?,
            val vnd: String?,
            val xag: String?,
            val xau: String?,
            val xdr: String?,
            val xlm: String?,
            val xrp: String?,
            val yfi: String?,
            val zar: String?,
            val bits: String?,
            val link: String?,
            val sats: String?
        )


        data class MarketCap(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class FullyDilutedValuation(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class TotalVolume(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class High24h(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class Low24h(
            val aed: Double,
            val ars: Double,
            val aud: Double,
            val bch: Double,
            val bdt: Double,
            val bhd: Double,
            val bmd: Double,
            val bnb: Double,
            val brl: Double,
            val btc: Double,
            val cad: Double,
            val chf: Double,
            val clp: Double,
            val cny: Double,
            val czk: Double,
            val dkk: Double,
            val dot: Double,
            val eos: Double,
            val eth: Double,
            val eur: Double,
            val gbp: Double,
            val gel: Double,
            val hkd: Double,
            val huf: Double,
            val idr: Double,
            val ils: Double,
            val inr: Double,
            val jpy: Double,
            val krw: Double,
            val kwd: Double,
            val lkr: Double,
            val ltc: Double,
            val mmk: Double,
            val mxn: Double,
            val myr: Double,
            val ngn: Double,
            val nok: Double,
            val nzd: Double,
            val php: Double,
            val pkr: Double,
            val pln: Double,
            val rub: Double,
            val sar: Double,
            val sek: Double,
            val sgd: Double,
            val thb: Double,
            @SerializedName("try")
            val tryX: Double,
            val twd: Double,
            val uah: Double,
            val usd: Double,
            val vef: Double,
            val vnd: Double,
            val xag: Double,
            val xau: Double,
            val xdr: Double,
            val xlm: Double,
            val xrp: Double,
            val yfi: Double,
            val zar: Double,
            val bits: Double,
            val link: Double,
            val sats: Double
        )


        data class PriceChange24hInCurrency(
            val aed: Double,
            val ars: Double,
            val aud: Double,
            val bch: Double,
            val bdt: Double,
            val bhd: Double,
            val bmd: Double,
            val bnb: Double,
            val brl: Double,
            val btc: Double,
            val cad: Double,
            val chf: Double,
            val clp: Double,
            val cny: Double,
            val czk: Double,
            val dkk: Double,
            val dot: Double,
            val eos: Double,
            val eth: Double,
            val eur: Double,
            val gbp: Double,
            val gel: Double,
            val hkd: Double,
            val huf: Double,
            val idr: Double,
            val ils: Double,
            val inr: Double,
            val jpy: Double,
            val krw: Double,
            val kwd: Double,
            val lkr: Double,
            val ltc: Double,
            val mmk: Double,
            val mxn: Double,
            val myr: Double,
            val ngn: Double,
            val nok: Double,
            val nzd: Double,
            val php: Double,
            val pkr: Double,
            val pln: Double,
            val rub: Double,
            val sar: Double,
            val sek: Double,
            val sgd: Double,
            val thb: Double,
            @SerializedName("try")
            val tryX: Double,
            val twd: Double,
            val uah: Double,
            val usd: Double,
            val vef: Double,
            val vnd: Double,
            val xag: Double,
            val xau: Double,
            val xdr: Double,
            val xlm: Double,
            val xrp: Double,
            val yfi: Double,
            val zar: Double,
            val bits: Double,
            val link: Double,
            val sats: Double
        )


        data class PriceChangePercentage1hInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage24hInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage7dInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage14dInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage30dInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage60dInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage200dInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class PriceChangePercentage1yInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )


        data class MarketCapChange24hInCurrency(
            val aed: Double,
            val ars: Double,
            val aud: Double,
            val bch: Double,
            val bdt: Double,
            val bhd: Double,
            val bmd: Double,
            val bnb: Double,
            val brl: Double,
            val btc: Double,
            val cad: Double,
            val chf: Double,
            val clp: Double,
            val cny: Double,
            val czk: Double,
            val dkk: Double,
            val dot: Double,
            val eos: Double,
            val eth: Double,
            val eur: Double,
            val gbp: Double,
            val gel: Double,
            val hkd: Double,
            val huf: Double,
            val idr: Double,
            val ils: Double,
            val inr: Double,
            val jpy: Double,
            val krw: Double,
            val kwd: Double,
            val lkr: Double,
            val ltc: Double,
            val mmk: Double,
            val mxn: Double,
            val myr: Double,
            val ngn: Double,
            val nok: Double,
            val nzd: Double,
            val php: Double,
            val pkr: Double,
            val pln: Double,
            val rub: Double,
            val sar: Double,
            val sek: Double,
            val sgd: Double,
            val thb: Double,
            @SerializedName("try")
            val tryX: Double,
            val twd: Double,
            val uah: Double,
            val usd: Double,
            val vef: Double,
            val vnd: Double,
            val xag: Double,
            val xau: Double,
            val xdr: Double,
            val xlm: Double,
            val xrp: Double,
            val yfi: Double,
            val zar: Double,
            val bits: Double,
            val link: Double,
            val sats: Double
        )


        data class MarketCapChangePercentage24hInCurrency(
            val aed: Double?,
            val ars: Double?,
            val aud: Double?,
            val bch: Double?,
            val bdt: Double?,
            val bhd: Double?,
            val bmd: Double?,
            val bnb: Double?,
            val brl: Double?,
            val btc: Double?,
            val cad: Double?,
            val chf: Double?,
            val clp: Double?,
            val cny: Double?,
            val czk: Double?,
            val dkk: Double?,
            val dot: Double?,
            val eos: Double?,
            val eth: Double?,
            val eur: Double?,
            val gbp: Double?,
            val gel: Double?,
            val hkd: Double?,
            val huf: Double?,
            val idr: Double?,
            val ils: Double?,
            val inr: Double?,
            val jpy: Double?,
            val krw: Double?,
            val kwd: Double?,
            val lkr: Double?,
            val ltc: Double?,
            val mmk: Double?,
            val mxn: Double?,
            val myr: Double?,
            val ngn: Double?,
            val nok: Double?,
            val nzd: Double?,
            val php: Double?,
            val pkr: Double?,
            val pln: Double?,
            val rub: Double?,
            val sar: Double?,
            val sek: Double?,
            val sgd: Double?,
            val thb: Double?,
            @SerializedName("try")
            val tryX: Double?,
            val twd: Double?,
            val uah: Double?,
            val usd: Double?,
            val vef: Double?,
            val vnd: Double?,
            val xag: Double?,
            val xau: Double?,
            val xdr: Double?,
            val xlm: Double?,
            val xrp: Double?,
            val yfi: Double?,
            val zar: Double?,
            val bits: Double?,
            val link: Double?,
            val sats: Double?
        )
    }


    data class CommunityData(
        @SerializedName("facebook_likes")
        val facebookLikes: Any,
        @SerializedName("twitter_followers")
        val twitterFollowers: Int?,
        @SerializedName("reddit_average_posts_48h")
        val redditAveragePosts48h: Double?,
        @SerializedName("reddit_average_comments_48h")
        val redditAverageComments48h: Double?,
        @SerializedName("reddit_subscribers")
        val redditSubscribers: Int?,
        @SerializedName("reddit_accounts_active_48h")
        val redditAccountsActive48h: Int?,
        @SerializedName("telegram_channel_user_count")
        val telegramChannelUserCount: Any
    )


    data class DeveloperData(
        val forks: Int?,
        val stars: Int?,
        val subscribers: Int?,
        @SerializedName("total_issues")
        val totalIssues: Int?,
        @SerializedName("closed_issues")
        val closedIssues: Int?,
        @SerializedName("pull_requests_merged")
        val pullRequestsMerged: Int?,
        @SerializedName("pull_request_contributors")
        val pullRequestContributors: Int?,
        @SerializedName("code_additions_deletions_4_weeks")
        val codeAdditionsDeletions4Weeks: CodeAdditionsDeletions4Weeks?,
        @SerializedName("commit_count_4_weeks")
        val commitCount4Weeks: Int?,
        @SerializedName("last_4_weeks_commit_activity_series")
        val last4WeeksCommitActivitySeries: List<Any>
    ) {

        data class CodeAdditionsDeletions4Weeks(
            val additions: Int?,
            val deletions: Int?
        )
    }


    data class Ticker(
        val base: String?,
        val target: String?,
        val market: Market?,
        val last: Double?,
        val volume: Double?,
        @SerializedName("converted_last")
        val convertedLast: ConvertedLast?,
        @SerializedName("converted_volume")
        val convertedVolume: ConvertedVolume?,
        @SerializedName("trust_score")
        val trustScore: String?,
        @SerializedName("bid_ask_spread_percentage")
        val bidAskSpreadPercentage: Double?,
        val timestamp: String?,
        @SerializedName("last_traded_at")
        val lastTradedAt: String?,
        @SerializedName("last_fetch_at")
        val lastFetchAt: String?,
        @SerializedName("is_anomaly")
        val isAnomaly: Boolean,
        @SerializedName("is_stale")
        val isStale: Boolean,
        @SerializedName("trade_url")
        val tradeUrl: String?,
        @SerializedName("token_info_url")
        val tokenInfoUrl: Any,
        @SerializedName("coin_id")
        val coinId: String?,
        @SerializedName("target_coin_id")
        val targetCoinId: String?
    ) {

        data class Market(
            val name: String?,
            val identifier: String?,
            @SerializedName("has_trading_incentive")
            val hasTradingIncentive: Boolean
        )


        data class ConvertedLast(
            val btc: Double?,
            val eth: Double?,
            val usd: Double?
        )


        data class ConvertedVolume(
            val btc: Double?,
            val eth: Double?,
            val usd: Double?
        )
    }
}